apiVersion: apps/v1
kind: Deployment
metadata:
  name: basil-eureka-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: base-spring-eureka
  template:
    metadata:
      labels:
        app: base-spring-eureka
    spec:
      containers:
      - name: base-spring-eureka-container
        image: basil.base-spring-eureka:latest
        ports:
        - containerPort: 8761